Pass current state of the definition to definition_helpers in APISpec.definition
marshmallow-code/apispec pull request #122
Opened 2017-03-17 01:44 UTC by martinlatrille

Now pass the current state of the definition (i.e. `ret`) as a `kwarg` to all definition helpers.

It will allow helpers to do modifications of nested value in the definition (like modifying a schema's property for example) without overriding the whole top-level dict (`properties`, in our example).

2017-03-17 08:29 UTC, lafrech commented
Looks good.

Note that this relies on the order in which the helpers are executed, which is the registration order: the order of the plugins in the list you pass at APISpec init. This is also the case for path helpers. This could be an issue if you need a different order for path helpers and definition helpers. But this is more of a theoretical issue, I don't think it would be blocking in practice. Anyway, there's no reason to block this PR until this is addressed.

Care to add a test before we can merge this?

Also, I suggest this change:

```python
- Definition: the current state of the definition of the schema
+ definition (dict): current state of the definition
```

2017-03-17 12:18 UTC, sloria requested changes
Once the test and small doc change have been made, this is good to merge. Thanks for the PR, and thanks @lafrech for reviewing.

2017-03-17 12:18 UTC, sloria commented on apispec/core.py
> +        In `kwargs`, you will find among other things:
To piggy-back on @lafrech 's suggestion, how about:

```
``kwargs`` will include (among other things):
- definition (dict): current state of the definition
```

2017-03-17 17:15 UTC, martinlatrille commented
Thanks for the review guys, I've edited the doc and added a test!

2017-03-17 17:15 UTC, martinlatrille commented on apispec/core.py
> +        In `kwargs`, you will find among other things:
Done!

2017-03-19 18:14 UTC, sloria approved these changes

2017-03-19 18:14 UTC, sloria commented
Looks good. Thanks for making those changes.

2017-03-19 18:14 UTC, merged