Allow default value for fields to be callable.
marshmallow-code/apispec pull request #131
Opened 2017-06-29 12:53 UTC by NightBlues

Hi there! As docstring 
https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L63 says the default value may be callable. I think it's a common use case, f.e. passing list or dict constructor to field.
```
from marshmallow import Schema, fields
class MySchema(Schema):
    numbers = fields.List(fields.Int, default=list)
```

2017-07-04 10:33 UTC, NightBlues commented
@sloria, what do you think about this?)

2017-07-10 12:22 UTC, sloria requested changes
Thanks @NightBlues for the PR. I think this makes sense, but I have a slight concern about the implementation. There's a possibility of swallowing a `TypeError` raised within the callable. We should probably just mirror the implementation from marshmallow:

```python
                    if callable(self.default):
                        return self.default()
                    else:
                        return self.default
```

2017-07-10 12:22 UTC, sloria commented
Once my comment above has been addressed and tests are added, this should be good to merge.

2017-07-12 10:17 UTC, NightBlues commented
@sloria is that better?

2017-07-12 12:09 UTC, sloria approved these changes

2017-07-12 12:09 UTC, sloria commented
Looks good to me. Thanks!

2017-07-12 12:09 UTC, merged