Permit auto generation of definition schema names
marshmallow-code/apispec pull request #167
Opened 2017-11-08 16:09 UTC by lebouquetin

The case we faced is the following one:

- we have a self referencing schema, lets call it NodeSchema.
- this schema is included in another schema - NodeList

When we try to define NodeList in APIspec, the NodeSchema is not yet reference, so its structure is inlined. As it is self referencing, the inline results in an infinite recursion, so it crashes

The global solution is to add definitions of our Schema in the right order. As we use APIspec in [hapic]( https://github.com/algoo/hapic/) (a generic auto-documented REST API framework), we can't assume that schema will be defined in the right order for APIspec.

There are two ways to get schemas defined in the right order:
1. first solution is to preprocess all the schema we have to document in order to add thems to apispec in the right order. It's not very elegant (but it works)
2. second solution is to define the rule to define name of a schema in the auto-generated documentation. This is quite easy to integrate in APIspec - this is the current PR.

How it works:
- if you do nothing special, APIspec keep on working as it already do.
- if you define a callable `schema_name_resolver_callable` at construction time of `APISpec`, then it will be used for auto-referencing required schemas.

We'd be happy this PR to be accepted fast, let us know if you are ok and/or if we should change some stuff for the PR to be accepted (naming, etc).

Damien

2017-11-09 09:27 UTC, yoichi requested changes

2017-11-09 09:27 UTC, yoichi commented on apispec/ext/marshmallow/__init__.py
> +        if spec.schema_name_resolver_callable:
spec can be None here (travis-ci test fails)

2017-11-09 09:27 UTC, yoichi commented on apispec/core.py
> +    :param callable schema_name_resolver_callable: callable who generate the schema definition name
What is the input and output of this callable? Could you add a test code to illustrate its usage?

2017-11-09 15:21 UTC, lebouquetin commented on apispec/ext/marshmallow/__init__.py
> +        if spec.schema_name_resolver_callable:
@buxx could you upgrade our code for fix ?

2017-11-09 15:22 UTC, lebouquetin commented on apispec/core.py
> +    :param callable schema_name_resolver_callable: callable who generate the schema definition name
@yoichi good question and query. @buxx you upgrade the documentation and add a test code to illustrate?

2017-11-09 15:26 UTC, buxx commented on apispec/core.py
> +    :param callable schema_name_resolver_callable: callable who generate the schema definition name
@lebouquetin I do that.

2017-11-09 15:31 UTC, buxx commented on apispec/ext/marshmallow/__init__.py
> +        if spec.schema_name_resolver_callable:
@lebouquetin done

2017-11-10 09:27 UTC, buxx commented on apispec/core.py
> +    :param callable schema_name_resolver_callable: callable who generate the schema definition name
done

2017-11-10 15:47 UTC, yoichi approved these changes

2017-11-10 15:47 UTC, yoichi commented
Thanks for clarifying the spec. I think this feature is useful.

* It would be nice if we have a test code for a new feature in order to avoid future regression. 
* "schema_name_resolver_callable" is a bit long. Does it make sense if simply "schema_name_resolver"?
* How about skipping spec.definition() call if "not definition_name"?

2017-11-10 16:21 UTC, buxx commented
@yoichi For your differents points: no problem, i  will do these changes next week :-)

2017-11-13 10:01 UTC, buxx commented
@yoichi It's seems we have a problem with python2.7: when json.dumps (used in tests) we got an `RuntimeError: dictionary changed size during iteration`. I guess it's because we add definitions when reading them (i don't know why it is working in python 3.x).
I don't found a smart solution. Maybe try to execute the code who parse definitions before ? Or disable this feature for python < 3.x ?

2017-11-17 10:10 UTC, buxx commented
@yoichi I found another way to implement this feature: auto-reference schemas when add a definition. Solve the problem of dynamic evolution of definition dict. Tests are green and all nested schemas are auto referenced correctly.

2017-12-07 08:58 UTC, buxx commented
Hello @yoichi @sloria we have no news since last month about this pull request. any problem with it ?

2017-12-07 14:29 UTC, sloria commented
@buxx Thanks for your patience and for getting this up to date. I'll try to take a look at this this weekend.

2017-12-09 23:26 UTC, merged

2017-12-09 23:27 UTC, sloria commented
Thanks for the PR!