Allow to access APISpec components in plugin init_spec
marshmallow-code/apispec pull request #539
Opened 2020-02-12 16:51 UTC by Colin-b

closes #538 

Note that I tried to manually follow flake8 as my corporate network is using a self signed certificate to perform "man in the middle" preventing Git to access flake8 repo on gitlab (so pre-commit was failing).

2020-02-12 17:01 UTC, lafrech requested changes
AFAIU, flake8 is fine. The CI issues are with black.

I don't understand your setup but I suppose you can pip install flake8 black and run them. Or just apply manually the changes in there: https://dev.azure.com/sloria/sloria/_build/results?buildId=2793&view=logs&j=7e27d0d1-c3b5-5589-c3a3-eb2d9b518da8&t=f9c3c3ee-9bfd-5d70-3f98-d6c193ea86e4.

Or wait until I get the time to do it myself.

Otherwise, this is fine. Just a nitpick in the test.

2020-02-12 17:01 UTC, lafrech commented on tests/test_core.py
> +        assert metadata["definitions"] == {
Use get_schema form tests/utils.py.

2020-02-12 17:26 UTC, Colin-b commented on tests/test_core.py
> +        assert metadata["definitions"] == {
Done :)

2020-02-12 17:27 UTC, Colin-b commented
> AFAIU, flake8 is fine. The CI issues are with black.
> 
> I don't understand your setup but I suppose you can pip install flake8 black and run them. Or just apply manually the changes in there: https://dev.azure.com/sloria/sloria/_build/results?buildId=2793&view=logs&j=7e27d0d1-c3b5-5589-c3a3-eb2d9b518da8&t=f9c3c3ee-9bfd-5d70-3f98-d6c193ea86e4.
> 
> Or wait until I get the time to do it myself.
> 
> Otherwise, this is fine. Just a nitpick in the test.

I manually applied flake8 before but I was unsure something else was performed by pre-commit lib.
I applied blake as well and it refactored the test :)

2020-02-14 22:38 UTC, lafrech approved these changes

2020-02-14 22:39 UTC, merged