Add IP fields to DEFAULT_FIELD_MAPPING
marshmallow-code/apispec pull request #892
Opened 2024-03-14 13:58 UTC by cjproud

This relates to https://github.com/marshmallow-code/flask-smorest/issues/623 where Swagger was not obeying `required=True` for the `IPv4` field. This adds the different IP fields to the DEFAULT_FIELD_MAPPING where the type is string the format is the IP address format.

2024-03-14 15:57 UTC, lafrech requested changes
Thanks. Looks good.

Please complete tests in /tests/test_ext_marshmallow_field.py:
- test_field2property_type
- test_field2property_formats

Does this solve https://github.com/marshmallow-code/flask-smorest/issues/623?

2024-03-14 15:57 UTC, lafrech commented on AUTHORS.rst
> +- Christian Proud `@cjproud <https://github.com/cjproud>`
Missing trailing underscore.

2024-03-15 00:48 UTC, cjproud commented on AUTHORS.rst
> +- Christian Proud `@cjproud <https://github.com/cjproud>`
Fixed in [e0fc7b0](https://github.com/marshmallow-code/apispec/pull/892/commits/e0fc7b04b5f3958f2042cd1fc894b66bd28fcb6f)

2024-03-15 00:49 UTC, cjproud commented
> Thanks. Looks good.
> 
> Please complete tests in /tests/test_ext_marshmallow_field.py:
> 
> * test_field2property_type
> * test_field2property_formats
> 
> Does this solve [marshmallow-code/flask-smorest#623](https://github.com/marshmallow-code/flask-smorest/issues/623)?

Yup this solves that issue 👍

2024-03-15 08:07 UTC, lafrech approved these changes
Thanks.

I think the original issue (https://github.com/marshmallow-code/flask-smorest/issues/623) could have be solved in marshmallow just by letting IP field inherit String (https://github.com/marshmallow-code/marshmallow/pull/2250), but this PR makes the documentation more complete by specifying the format.

2024-03-15 08:08 UTC, merged